### ISSUE TITLE
Migrating projects to androidx while using evernote results in JetifyTransform error.

### ISSUE THREAD

**Issue by 0megaD** [evernote/android-state#56] opened 2018-07-20 08:44 UTC
I'm trying to migrate to androidx and we use your library in our project.
This is currently causing an issue in our project:

> * What went wrong:
> Could not resolve all files for configuration ':app:debugAnnotationProcessorClasspath'.
> > Failed to transform file 'android-4.1.1.4.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
>    > Failed to transform '/Users/daniel/.gradle/caches/modules-2/files-2.1/com.google.android/android/4.1.1.4/3fb039385e71e9aa2ba547ea9ea8caa34a4ffac7/android-4.1.1.4.jar' using Jetifier. Reason: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 2 of 4-byte UTF-8 sequence.. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file

This is stopping us from migrating to Google's new Android support packages.
Do you have any idea on what might be causing this? I also filed a bug ticket on Google's tracker, but perhaps there's something you can do as well.

**Comment by vRallev** [comment] 2018-07-20 23:19
The annotation processor uses this artifact as a dependency, but it doesn't need to be transformed. Could you please link the issue from the Google tracker? A tiny sample app would also be helpful.

**Comment by vRallev** [comment] 2018-07-23 16:01
Thanks, I hope they'll add a fix.

**Comment by jemshit** [comment] 2018-09-12 07:56
Just found that build is failing because of this dependency. Any workaround ?

**Comment by vRallev** [comment] 2018-09-24 03:16
I released version `1.4.0`, where I migrated all dependencies to AndroidX. It would be great if someone could test their projects again. I don't have high hopes, but maybe the issue is fixed.

**Comment by jemshit** [comment] 2018-09-24 07:35
@vRallev same error :/

**Comment by vRallev** [comment] 2018-09-24 13:33
Dang, thanks for letting me know

**Comment by vRallev** [comment] 2018-09-24 20:33
What about `3.3.0-alpha11`?

**Comment by janbina** [comment] 2018-09-24 20:39
Oh, I thought `alpha10` is latest... but no, same error with `alpha11`

**Comment by markus2610** [comment] 2018-09-25 15:01
I can confirm that. android studio 3.3 Preview, 3.3.0-alpha11

**Comment by felixdivo** [comment] 2018-09-28 13:58
Same problem with version library version 1.4.0 on Android Studio 3.2 stable.

**Comment by felixdivo** [comment] 2018-09-28 14:05
I have a slightly different "stack trace" since I am using kapt:

```
* What went wrong:
Execution failed for task ':app:kaptGenerateStubsDebugKotlin'.
> Could not resolve all files for configuration ':app:kapt'.
   > Failed to transform file 'android-4.1.1.4.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
      > Failed to transform 'C:\Users\Felix\.gradle\caches\modules-2\files-2.1\com.google.android\android\4.1.1.4\3fb039385e71e9aa2ba547ea9ea8caa34a4ffac7\android-4.1.1.4.jar' using Jetifier.
        Reason: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException:
        Ungültiges Byte 2 von 4-Byte-UTF-8-Sequenz..
        (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file.
```

`Ungültiges Byte 2 von 4-Byte-UTF-8-Sequenz` is German (seemingly the only German piece of text in the entire Android Studio ^^) and translates to `Invalid Byte 2 of 4-Byte-UTF-8-Sequence` (like above).

**Comment by MFlisar** [comment] 2018-09-30 17:05
I have the same stacktrace like you @felixdivo 

But for now I @janbina 's solution is working

**Comment by floynn** [comment] 2018-10-03 17:44
I managed to make it work by excluding android dependency
```
kapt ("com.evernote:android-state-processor:1.4.0") {
        exclude group: 'com.google.android', module: 'android'
    }
```
Also just put up a PR which should do the same fix from library side.

**Comment by vRallev** [comment] 2018-10-07 00:37
@floynn I've merged your fix and it works well with Kotlin and Kapt. But for some reason it's not working with plain Java projects and `annotationProcessor`. In this case the Android classes can't be found during compilation. I'm still trying to find out why this is. Any idea?

**Comment by vRallev** [comment] 2018-10-07 02:10
I was able to resolve the problem. The issue should be fixed now. Please give version `1.4.1` a try and let me know if it's really fixed for you all. Thanks for all the help!

**Closed by vRallev** 2018-10-07 02:10 UTC
Labels: bug, needs-info

**Comment by floynn** [comment] 2018-10-08 17:05
> I was able to resolve the problem. The issue should be fixed now. Please give version `1.4.1` a try and let me know if it's really fixed for you all. Thanks for all the help!

@vRallev Sorry for the late response. Thank you for the quick fixes and new release! `1.4.1` works fine for me.

**Comment by janbina** [comment] 2018-10-08 20:06
It's fixed for me as well, thanks.

**Comment by felixdivo** [comment] 2018-10-08 22:06
Thank you! I can confirm it as well. 😄
