### ISSUE TITLE
Recompilation with sight changes resulted evernote SavedState RestoreState no longer work (reoccur)

### ISSUE THREAD

**Issue by elye** [evernote/android-state#33] opened 2017-09-06 13:50 UTC
This is originally reported in https://github.com/evernote/android-state/issues/21.
The issue is deem resolved when having a single Kotlin Class, and use gradle-4.0-all.zip

With the latest gradle-4.1-all.zip, the issue reoccurs now, and happens even when there's a single Kotlin class. 

I have made changes to the simple project in https://github.com/elye/issue_evernote_state. (using version 1.1.4 of android-state library)
Step to reproduce the issue.

1.) Clone the repo
2.) Compile and run it on a device (with don't keep activity on)
3.) On background the App, and foreground. It will toast State is correct
4.) Now go to MainActivity.java and comment out Log.d("Nothing", "Just log");
5.) Compile it (not clean and recompile, but just a simple click on compile)
6.) Run the App (make sure don't keep activity is on)
7.) On background the App, and foreground. It will toast State is wrong

Note: the State is wrong is where the state is not able to retrieve successfully.
Once you could replicate this, means you could replicate the bug. Check the code, it's simple logic that could be understand, where State is correct is always expected upon foreground (for a Don't Keep Activity on device).

Additional steps if you like
8.) Perform a clean, and recompile the code.
9.) Compile and run it on a device (with don't keep activity on)
10.) On background the App, and foreground. It will toast State is correct

Well, a clean compilation will ensure it get linked back.

The old issue is reoccurring now. It is hurting us much and confuse us of actual issue, vs the issue caused by state not restored properly due to this Android-State library issue/bug.

**Comment by talentprince** [comment] 2017-09-08 00:25
I really think this is a big issue, that I have also encounter, hope owner team can fix it

**Comment by vRallev** [comment] 2017-09-10 14:03
I can reproduce the problem with your sample and honestly don't have an idea what's wrong. For me it's a bug in the build tools, I've filed an issue here: https://issuetracker.google.com/issues/65519025

Right now I can't do anything.

**Comment by vRallev** [comment] 2017-10-14 10:13
It looks like this issue is fixed in the latest Gradle Plugin: http://androidstudio.googleblog.com/2017/10/android-studio-30-rc-1-now-available.html See the first issue "Missing classes in APK". Can you give it a try?

**Comment by vRallev** [comment] 2017-11-01 13:01
The issue should be fixed now with the release of the Android Gradle Plugin 3.0.0

**Closed by vRallev** 2017-11-01 13:01 UTC

**Comment by elye** [comment] 2017-11-22 23:01
Tested, looks like Gradle Plugin 3.0.0 fix the issue. Great! Thanks!
