### ISSUE TITLE
Build error with Android Gradle plugin 2.4.0-alpha3

### ISSUE THREAD

**Issue by jaimeagudo** [evernote/android-state#13] opened 2017-03-25 18:35 UTC
Any clues about why is this?

```
Error:Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.evernote.android.state.StateProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/evernote/android/state/State
```
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDevDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:206)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:187)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:130)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 20 more

```

I am on Android Studio 2.4 Preview 2
Build #AI-171.3804685, built on March 15, 2017
JRE: 1.8.0_112-release-b736 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

My `build.gradle`

```
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        jcenter()
        maven { url 'https://jitpack.io' }
        maven {
            url "https://clojars.org/repo/"
        }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'me.tatarka:gradle-retrolambda:3.6.0'

    }
}


apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'io.fabric'
//apply plugin: 'com.f2prateek.javafmt'



android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

    defaultConfig {
        applicationId "site.paid2party.android"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-DEBUG'
            ext.enableCrashlytics = true
            testCoverageEnabled = false
            debug {
                debuggable true
            }
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            debug {
                debuggable true
            }
        }
        buildTypes.each {
            it.buildConfigField 'String', 'TEST_KEY', TEST_KEY
        }
    }
    dexOptions {
        javaMaxHeapSize "2048M"
        preDexLibraries = false
    }
    productFlavors {
        // When building a variant that uses this flavor, the following configurations
        // override those in the defaultConfig block.
        dev {
            // To avoid using legacy multidex, set minSdkVersion to 21 or higher.
            minSdkVersion 21
            versionNameSuffix "-dev"
            applicationIdSuffix '.dev'
            resConfigs "en", "xxhdpi"
        }

        prod {
            // If you've configured the defaultConfig block for the release version of
            // your app, you can leave this block empty and Gradle uses configurations in
            // the defaultConfig block instead. You still need to create this flavor.
            // Otherwise, all variants use the "dev" flavor configurations.
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://maven.fabric.io/public' }

}

// Define versions in a single place
ext {


    // App dependencies
    supportLibraryVersion = '25.2.0'
    playServicesVersion = '10.2.0'

}
//https://developer.android.com/topic/libraries/support-library/packages.html
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile "com.android.support:appcompat-v7:${supportLibraryVersion}"
    compile "com.android.support:cardview-v7:${supportLibraryVersion}"
    compile "com.android.support:design:${supportLibraryVersion}"
    compile "com.android.support:support-v4:${supportLibraryVersion}"
    compile "com.android.support:recyclerview-v7:${supportLibraryVersion}"
    compile "com.android.support:palette-v7:${supportLibraryVersion}"
    compile "com.android.support:gridlayout-v7:${supportLibraryVersion}"

    compile "com.google.android.gms:play-services-identity:$playServicesVersion"
    compile "com.google.android.gms:play-services:$playServicesVersion"
    compile "com.google.android.gms:play-services-places:$playServicesVersion"
    compile "com.google.android.gms:play-services-location:$playServicesVersion"

    compile('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
        transitive = true;
    }

    compile 'com.evernote:android-state:1.0.5'
    annotationProcessor 'com.evernote:android-state-processor:1.0.5'

    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'
    testCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'


}
```

**Comment by vRallev** [comment] 2017-03-25 20:09
Which Android plugin are you using? I can't spot it. Can you provide a demo project that reproduces the issue?

**Comment by ersin-ertan** [comment] 2017-03-25 21:32
I'm getting the same error too
```java
Error:Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.evernote.android.state.StateProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/evernote/android/state/State
```
I just switched from `apt` to `annotationProcessor`

**Comment by jaimeagudo** [comment] 2017-03-25 22:13
root `build.gradle`

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.4.0-alpha1'
        classpath 'io.fabric.tools:gradle:1.+'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files


///////////////////////////////////////
        // Required plugins added to classpath to facilitate pushing to Jcenter/Bintray
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.4'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
///////////////////////////////////////
    }
}

allprojects {
    repositories {
        jcenter()
    }
}


```

**Comment by vRallev** [comment] 2017-03-25 22:18
Could you try the Android gradle plugin version `2.3.0` instead of `2.4.0-alpha1`? We have a similar setup and don't run into such an issue.

**Comment by ersin-ertan** [comment] 2017-03-25 22:22
I can confirm that `2.3.0` does not give the build error.

**Comment by jaimeagudo** [comment] 2017-03-25 22:28
Confirmed it's the alpha plugin... sorry for bothering but google didn't even give me a clue of any related issue except for other evernote component so I thought it could be a particular tweak you use to have in your libraries. Thanks again 👍

**Comment by vRallev** [comment] 2017-03-25 22:29
Maybe you can give alpha3 a try. But it definitely looks like a bug in the gradle plugin.

**Comment by ersin-ertan** [comment] 2017-03-25 22:29
I'm using alpha3
https://github.com/evernote/android-state/issues/13#issuecomment-289240950

**Comment by vRallev** [comment] 2017-03-26 21:46
Yeah, I'll try to find the reason for this issue.

**Comment by vRallev** [comment] 2017-03-27 16:55
I was able to reproduce the issue, but unfortunately I don't know what's wrong. I've created a bug report here: https://code.google.com/p/android/issues/detail?id=267031

**Comment by vRallev** [comment] 2017-04-07 09:52
Update: The workaround in the ticket works for me:
```groovy
android {
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }
    }
}
```

However, plugin alpha4 has another problem.

**Comment by ersin-ertan** [comment] 2017-04-07 10:04
If the other problem you are talking about is this, then there is a solution: 
https://androidstudio.googleblog.com/2017/04/android-studio-24-preview-4-is-now.html
Known Issues

After updating the Android plugin version, you need to stop the Gradle daemon to apply the update (Issue 267099). Otherwise, Gradle sync and builds fail with the following error: Could not initialize class com.android.ide.common.util.ReadWriteProcessLock, Failed to notify build listener, or java.lang.ExceptionInInitializerError.
To stop the daemon, you can either restart Android Studio, or enter the following command in the IDE's Terminal window: ./gradlew --stop. Gradle restarts the daemon for you the next time you sync or build your project.

**Comment by vRallev** [comment] 2017-04-07 10:43
Oh, yes, didn't notice this issue. Thanks!

I keep this issue open until the final version is released. Hopefully it won't be necessary to apply the workaround.

**Comment by vRallev** [comment] 2017-05-13 08:38
I finally figured out what's wrong and now bundle the library classes in the annotation processor jar. This will be fixed in the next version. If you want, you can give the snapshot build a try:
```groovy
repositories {
    jcenter()

    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

dependencies {
    compile 'com.evernote:android-state:1.0.7-SNAPSHOT'
    kapt 'com.evernote:android-state-processor:1.0.7-SNAPSHOT'
}
```

**Closed** 2017-06-05 11:15 UTC
Labels: bug
