### ISSUE TITLE
Recompilation with sight changes resulted evernote SavedState RestoreState no longer work

### ISSUE THREAD

**Issue by elye** [evernote/android-state#21] opened 2017-06-14 12:22 UTC
When using evernote Android-State (v1.0.6 ... also tested with v1.1.0), a clean compilation will always work. 

However if there's a minor code change, and I perform some recompilation (without clean compilation), the annotation processor generated `save` and `restore` is no longer accessible, hence causing the savedstate not accessible.

A clean compilation will restore the issue. (e.g. a new clean `save` and `restore` is generated etc).

Suspect the issue with the annotation processor handling of recompilation process, not able to link back to the generated code.

**Comment by vRallev** [comment] 2017-06-14 12:56
Can you attach one of the generated classes after a clean build and the 2nd build?

**Comment by elye** [comment] 2017-06-14 14:50
For the first clean compile, from the below, I could then trace from

```
    public static <T> void saveInstanceState(@NonNull T target, @NonNull Bundle state) {
        Injector.Object<T> injector = safeGet(target, Injector.Object.DEFAULT);
        injector.save(target, state);
    }

    public static <T> void restoreInstanceState(@NonNull T target, @Nullable Bundle state) {
        if (state != null) {
            Injector.Object<T> injector = safeGet(target, Injector.Object.DEFAULT);
            injector.restore(target, state);
        }
    }
```

to the generated class 

```
public class MyClass$$StateSaver<T extends MyClass> extends Injector.Object<T> {
  private static final HashMap<String, Bundler<?>> BUNDLERS = new HashMap<String, Bundler<?>>();

  private static final InjectionHelper HELPER = new InjectionHelper("my.package.app.ui.fragments.MyClass$$StateSaver", BUNDLERS);

  static {
  }

  @Override
  @SuppressWarnings("unchecked")
  public void save(T target, Bundle state) {
    HELPER.putParcelable(state, "firstVariable", target.firstVariable);
    HELPER.putBoolean(state, "secondVariable", target.secondVariable);
    HELPER.putInt(state, "thirdVariable", target.thirdVariable);
  }

  @Override
  @SuppressWarnings("unchecked")
  public void restore(T target, Bundle state) {
    target.firstVariable = HELPER.getParcelable(state, "firstVariable");
    target.secondVariable = HELPER.getBoolean(state, "secondVariable");
    target.thirdVariable = HELPER.getInt(state, "thirdVariable");
  }
}
```

However, after some minor edit on unrelated code, the second compile (not clean one)... I could trace to the Abstract Class

```
    public abstract static class Object<T> extends Injector {
        /*package*/ static final Object<?> DEFAULT = new Object<java.lang.Object>() {
            @Override
            public void restore(java.lang.Object target, Bundle state) {
                // no op
            }

            @Override
            public void save(java.lang.Object target, Bundle state) {
                // no op
            }
        };

        public abstract void restore(T target, Bundle state);

        public abstract void save(T target, Bundle state);
    }
```.

The link to the generated class is no longer there some how. A clean build would solve the problem.

**Comment by vRallev** [comment] 2017-06-14 15:01
With "trace from ... to" you mean in Android Studio? Could you check if the class is in the generated build folder nonetheless?

We didn't notice the problem so far and I tried to reproduce it. Could you a provide a sample for me?

**Comment by elye** [comment] 2017-06-14 15:08
"trace", meaning in debug mode, trace the code flow in Android Studio (F8 step in).
Yes, I still see the class in build/generated/source/kapt/FlavorDebug/...

Not sure if I could reproduce it using a small project. Will let you know if possible.

**Comment by vRallev** [comment] 2017-06-14 16:19
Could this be a problem with packaging the classes? It sounds like the generated classes aren't picked up anymore in the 2nd run. A sample would be great, although it doesn't sound like an issue with the library.

**Comment by elye** [comment] 2017-06-15 07:52
Hello vRallev,

I manage to create a simple project in https://github.com/elye/issue_evernote_state.
Step to reproduce the issue.

1.) Clone the repo
2.) Compile and run it on a device (with don't keep activity on)
3.) On background the App, and foreground. It will toast `State is correct`
4.) Now go to MainActivity.java and comment out `Log.d("Nothing", "Just log");` 
5.) Compile it (not clean and recompile, but just a simple click on compile)
6.) Run the App (make sure don't keep activity is on)
7.) On background the App, and foreground. It will toast `State is wrong`

Note: the State is wrong is where the state is not able to retrieve successfully.
Once you could replicate this, means you could replicate the bug. Check the code, it's simple logic that could be understand, where `State is correct` is always expected upon foreground (for a Don't Keep Activity on device).

Additional steps if you like
8.) Perform a clean, and recompile the code.
9.) Compile and run it on a device (with don't keep activity on)
10.) On background the App, and foreground. It will toast `State is correct`

Well, a clean compilation will ensure it get linked back.

I'm using Android Studio 2.3.2 and gradle-3.3. Hopes you could replicate this issue on your end.

**Comment by elye** [comment] 2017-06-15 12:43
vRallev, I have tried on `distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-all.zip`. The issue still persist. Removing `apply plugin: 'kotlin-kapt'` works for the small design, but for the actual design, we'll face some Dagger recompilation issue. Each time the a double compilation required. Perhaps that's the reason also the issue is covered, as that would force a Kapt recompilation. So both option doesn't work for us.

Maybe you could launch a bug report issue to Kapt?

**Comment by vRallev** [comment] 2017-06-15 12:49
Did you sync Android Studio after changing the Gradle version? What happens if you install the apk with Gradle directly in a terminal (`./gradlew installDebug`)?

I wanted to raise an issue, but I cannot reproduce it anymore with the latest stable tools. If you have a sample with Gradle 4.0, then it's better if you raise the issue.

**Comment by elye** [comment] 2017-06-15 13:33
hi vRallev, I have explicitly test again with the small design with `distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-all.zip`. It still exist, using the compilation from Android Studio. Gradle sync has been done. Try it on your side, you should see it too.

Apparently `./gradlew installDebug` is always good. (even for old gradle)

Perhaps not a Kapt issue, but incremental compilation issue?

**Comment by vRallev** [comment] 2017-06-15 17:00
Yes, I had made more changes. With Gradle 4.0 and one Kotlin class I couldn't reproduce the issue in the sample anymore
```kotlin
package com.elyeproj.evernotestateissue

class TestKotlinClass {

}
```

**Comment by elye** [comment] 2017-06-16 13:45
That's very interesting. Yes, with a single Kotlin class, then having `distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-all.zip` would not replicate the issue. Given that evernote/android-state is targeting those want to have both Java & Kotlin in the project, hence this is an acceptable solution.

Thanks vRallev. 

ps: I think it's important to note this in readme etc, so user who encounter this issue is aware of the resolution.

**Comment by vRallev** [comment] 2017-06-16 16:59
Well, it's addressed in the README already. It says for only Java projects you should use `annotationProcessor` instead of `kapt`. I think we can close the issue, right?

**Comment by elye** [comment] 2017-06-18 14:10
I'm fine with that. If it is just Java project, perhaps the user could just use icepick.
Thanks for following up with the issue. Hope the other user who face the problem found the resolution here. Cheers.

**Comment by vRallev** [comment] 2017-06-18 16:37
Why icepick? This project works fine without Kotlin. It also has a few advantages over icepick. If you setup the project like described, then it works
```groovy
dependencies {
    compile 'com.evernote:android-state:1.1.0'
    // Java only project
    annotationProcessor 'com.evernote:android-state-processor:1.1.0'

    // Kotlin with or without Java
    kapt 'com.evernote:android-state-processor:1.1.0'
}
```

**Closed by vRallev** 2017-06-18 16:37 UTC
